### PR TITLE
suggestion for channel

### PR DESCRIPTION
**Pull request by IGNRexI**
it is easier to name in different languages
not tried!
image

### CODE REVIEW

**Comment by LoveBeforT** [comment]
this doesn't exist on some clients,such as chinese client , EU-RU client ,etc

**Comment by IGNRexI** [comment]
Didn't you make web css js img directories?

**Comment by IGNRexI** [comment]
can you look at discord

**Comment by IGNRexI** [comment]
Tried now but didn't xd
Can you move channel names to server.conf?
editable file to at least change the channel names

**Comment by LoveBeforT** [comment]
I'll try

**Pull request closed without merging**
